### PR TITLE
add support for mapping of generic type definitions

### PR DESCRIPTION
**Pull request by ibrahimbensalah**
Usage:
> objectContainer.RegisterTypeAs(typeof(Impl<>), typeof(Interface<>))

### CODE REVIEW

**Comment by ibrahimbensalah** [comment]
Just to be very clear about this, *generic type definition* is not the same as *generic type*.

**Comment by darrencauthon** [comment]
Hello @ibrahimbensalah !

I want to say first... this is great.  See, I throw out challenges to devs all the time, and 99% of the time they just vanish.  You are now have "elite" status in my mind, as you are a dev that will put code to ideas.  That's great!

Two points first:

1.)  I'm having trouble distinguishing your changes from the library itself... like the "ShouldAllowOverrideRegistrationBeforeResolve" method at the top.  It looks like you deleted it, then it appears as a new method below.  Perhaps it was just whitespace formatting that caused this?  

But either way, it's preferable for PRs to have only the changes necessary to implement the change.  It makes review much, much easier.

2.)  Have you tried building SpecFlow with this change?  This library is copy-pasted into the project here (https://github.com/techtalk/SpecFlow/blob/master/lib/BoDi/BoDi.cs)... it's the actual C# file, not a link to a library.  This means that you could drop your new method into it, build the project, and then you have a SpecFlow.dll that you can use to make this work.

3.)  How does this fit with regards to using a separate IoC container?

I guess what I got from our previous conversation is that you (?) or other devs didn't just need this method - you needed it threaded through your own IoC container.  If that's the case, this is a positive step in that direction, but I still think you're going to hit the same problems once you try to swap in your own IoC container.

**Comment by ibrahimbensalah** [comment]
1) I suppose it's just a formatting issue of my local IDE, Sorry about that I didnt notice. I just added new unit tests without modifiying the existing ones. I believe this PR consists of only the nescessary changes to make it possible to register based on generic type definitions, and nothing more.
2) I can do that, but do you mean I have to submit new PR for the SpecFlow repo instead of BoDI?
3) It doesnt. but the next PR will be, I think there was some confusion about the scope of the previous discussion. I wasnt thinking about replacing ObjectContainer, neither about the lifetime management of the resolved objects. I was only talking about the construction of types and resolving dependencies as a pure functional task. So basically just extending ObjectContainer.CreateObject not including the management for the constructed objects.

**Comment by darrencauthon** [comment]
@ibrahimbensalah 

Regarding (2), you don't have to submit a PR to SpecFlow... it would just give you a **real-world** implementation of your idea.  

So here's what I used to do with SpecFlow and new changes:  I'd build my own custom dll of SpecFlow with the features that I wanted, and then I'd use them.  In production.  Or, err, tests for real production applications.  I'd work out any bugs during common usage, and by the time that I submitted the PR I was very confident that the code was vetted.

Here's the thing:  What programmers think code should do and how code should work is often very wrong.  We (myself included) are very poor at architecting the right solution to the problem the first time.  It always takes iterations, failure, and fixing before the right result is reached.  

I prefer to wait for some of that failure to get worked out before I put a public interface on an OSS project.  Of course, users will find things **I** didn't see, so it's sort of a balancing act.

This change is so different, I would suggest using it in a real app with real tests to vet the benefits gained.

And it's up for others to decide, too.  You'd have to publish this change to SpecFlow, and I'll be honest:  It's going to be a tough argument.  But it's much easier if you have proof of possibilities. :)

**Comment by ibrahimbensalah** [comment]
Allright, this is my plan, first there was a bug in my code that showed up after I executed **2)**, second, I will publish a new SpecFlow nuget package as a prerelease version on my own nuget domain, I will name it SpecFlow.1.9.0-beni (with beni as my nickname but i am not sure about the version number).

**Comment by darrencauthon** [comment]
Ahhh... my advice would be to not publish a SpecFlow-ish library to nuget... just for Nuget's sake.  I'm sure they don't want a bunch of one-off solutions published for public consumption.

I remember the pre-Nuget days when it was ok to reference a dll! :smile:

**Comment by ibrahimbensalah** [comment]
@darrencauthon @gasparnagy this change is fully tested in two big projects which contain various (probably all) aspects of SpecFlow and is working perfectly. Is there any chance we can get this into a new version of nuget package?

**Comment by gasparnagy** [comment]
@ibrahimbensalah i will check it once more on Tuesday when i'm back.

**Comment by gasparnagy** [comment]
@ibrahimbensalah merged. thx for the extension and sorry that it took so long... ;-)

**Pull request merged**
